# base metadata
name: find-islands-ecs
version: null
tags: []
description: null
schedule: null

# flow-specific fields
flow_name: null
entrypoint: null
path: null
parameters: {}
parameter_openapi_schema: null

# infra-specific fields
work_pool:
  name: ecs
  work_queue_name: null
  job_variables: {}